### PR TITLE
Add robots.txt

### PR DESCRIPTION
**Pull request by herzog31**
* Add `draft.robots.txt` as a blueprint for customers.

Test URLs:
- Before: https://main--aem-boilerplate-commerce--hlxsites.hlx.live/
- After: https://robots2--aem-boilerplate-commerce--hlxsites.hlx.live/

### CODE REVIEW

**Comment by herzog31** [comment]
@hannessolo @dicagno Can you think of anything else that we should add to this file?

**Comment by hannessolo** [comment]
Does this take into account luma bridge pages? Should it also disallow pages like /account ?

**Comment by herzog31** [comment]
@hannessolo Good point. All of those pages should already be excluded via metadata `<meta name="robots" content="noindex, nofollow">` e.g. https://main--aem-boilerplate-commerce--hlxsites.hlx.live/customer/account. We could move those over to the `robots.txt`.

**Comment by justinconabree** [comment]
Hi @herzog31 here's what we've seen are good paths to exclude in our projects:
```
/drafts/**
/enrichment/**
/experiments/**
/fragments/**
/tools/**
/nav
/footer
```
Note this was taken from the `exclude` from helix-query feeding our sitemap so the pattern might be different.

**Comment by herzog31** [comment]
Thanks @justinconabree, I added some of your suggestions 👍

**Pull request merged**
