### PR TITLE
USF 1629 - Add coupon container in cart

### PR DESCRIPTION
**Pull request by cctina516**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix Ticket: https://jira.corp.adobe.com/browse/USF-1629

Test URLs:
- Before: https://develop--aem-boilerplate-commerce--hlxsites.aem.live/
- After: https://cart-coupons-two--aem-boilerplate-commerce--hlxsites.aem.live/

### CODE REVIEW

**Review by anthoula — APPROVED** [review]

**Comment by ericeoeur** [comment]
@cctina516 QA Passed.

**Comment by ericeoeur** [comment]
@cctina516 please review the checkout coupons experience: as the removal of coupons are not being applied to the order summary totals.

**Comment by cctina516** [comment]
@ericeoeur 

1. Checkout coupon experience. As we discussed with @jcalcaben , it looks like an issue with the EstimateShopping container that checkout dropin uses, which doesn't emit an `estimate/shipping` event when the coupon is applied to the cart. Will create a bug ticket for it.
2. The "estimated tax and shipping" slot. It doesn't seem to do with the coupon container, but with Estimated shipping and tax being updated with any re-render. 

Initial state with no coupon applied: 
Screen Shot 2024-11-13 at 10 47 02 AM

Increase the quantity to 2, still no coupon applied:
Screen Shot 2024-11-13 at 10 47 09 AM

We can see the Estimated shipping and tax being activated regardless of any coupon actions. Therefore the issue is not with the coupon container, Will create a ticket for it. 

3. checking...

**Comment by ericeoeur** [comment]
Thanks @cctina516 QA approved. Will merge.

**Pull request merged**
